### ISSUE TITLE
Figure out how the value can be kept fixed in case of gold custody fees. 

### ISSUE THREAD

**Issue by robvanmieghem** [nbh-digital/eurochain#2]
In the case of gold custody fees, the value of the backing gold tokens or physical gold will decrease while this is not covered by te shortposition.  This is not covered by the [eurotoken concept](https://github.com/nbh-digital/eurochain/blob/master/docs/concept.md#eurotoken-concept)

**Comment by gmachtel** [comment]
If I understood well Raj, we can apply the same logic s for gold, being additional 0.0025% of eurotoken considered as unspendable on daily basis. The risk on the difference for the hedging will be taken by NBH Markets, no worry about that on the eurochain.

**Comment by gmachtel** [comment]
From NBH-Digital perspective, no separate behaviour than for GFT.
